# Floorplan parameters
## General
wall_thickness = 0.2
num_turns = 1
turn_direction = "alternating" # Options: "alternating", "random", "clockwise", "counterclockwise" but clockwise and counterclockwise are broken
## Rooms
num_rooms = 6
room_wall_length = 3.7
room_spacing = 0 # wall to wall spacing
## Doorway
doorway_width = 0.8
doorway_length = 0
## Hallway
hallway_width = 1
hallway_end_padding = 1.45 # Recommended value for vibes: (room_wall_length - doorway_width) / 2

# Output options
output = "output/floorplan.png"
resolution = 0.01
debug = false
skip_validation = false
