# Floorplan parameters
## General
wall_thickness = 0.2
num_turns = 3
turn_direction = "random"  # Options: "alternating", "random", "clockwise", "counterclockwise" but clockwise and counterclockwise are broken
# seed = 0
max_retries = 1
## Rooms
num_rooms = 6  # STALE: To use the minimum hallway length, set this to 3 * (num_turns + 1) + 1
room_wall_length = 3.7
room_spacing = 0  # Wall-to-wall spacing
## Doorway
doorway_width = 0.8
doorway_length = 0
## Hallway
hallway_width = 1.8
hallway_end_padding = 1.45  # Recommended value for vibes: (room_wall_length - doorway_width) / 2
num_open_spaces = 1

## Obstacles
obstacles_enabled = true
num_obstacles = 20
obstacle_length = 0.2  #  This requires balancing between hallway width/room size, obstacle clearance, and your lidar's angular resolution.
                       #  It should be small enough that your robot can go around it in a hallway or room, but large enough for your lidar to see it.
obstacle_clearance = 0.4  # This should be your robot's radius plus some buffer
obstacle_spacing = 0
obstacle_placement = "both"  # Options: "rooms", "hallways", "both"

## Robot Spawn Positions
robot_radius = 0.255
num_robots = 5
robot_min_clearance = 0.1
spawn_export_filename = "world_config.yaml"
clustered_robot_spawns = true  # If true, robots are clustered. If false, all robots are placed randomly.

## Extra Points
num_extra_points = 3
extra_point_radius = 0.5
extra_point_min_clearance = 0.0

# Output options
output = "output/floorplan.png"
resolution = 0.01
debug = false
skip_validation = false
